services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
      - "/docker/appdata/filebrowser:/database"
      - "/docker/appdata/filebrowser:/config"
      - "/srv/www/files:/srv"
    restart: unless-stopped
    ports:
      - "8090:80"
    user: "1001:1001"