services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 997:997 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_ENABLEINSIGHTSCOLLECTOR: false
    volumes:
      - "/docker/appdata/navidrome:/data"
      - "/media/music:/music:ro"
