services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    privileged: true
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - 9323:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro